repos:
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        description: Format files with rustfmt.
        entry: bash -c 'cargo fmt'
        language: rust
        files: \.rs$
        args: []

# pre-commit.ci bot configuration
ci:
  autofix_prs: false
  autofix_commit_msg: |
    '[pre-commit.ci ðŸ¤–] Reformat PR'
  # How often to send PR for updating pre-commit-config.yaml versions
  autoupdate_schedule: quarterly
