[package]
name = "boom-api"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-rt = "2.10.0"
actix-web = "4.9.0"
futures = "0.3.31"
mongodb = "3.1.0"
serde = "1.0.215"
serde_json = "1.0.138"

[dependencies.uuid]
version = "1.16.0"
features = ["v4"]
